services:
  db:
    image: mysql:8.4
    container_name: gympoint-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mitre280
      MYSQL_DATABASE: gympoint
    ports:
      - '3308:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ../backend/db:/docker-entrypoint-initdb.d
    networks:
      - gympoint-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend_stable:
    image: project-gympoint-backend:stable
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mitre280
      DB_NAME: gympoint
      DB_PORT: 3306
      PORT: 3000
      JWT_SECRET: clave_super_secreta_para_tokens
      JWT_REFRESH_SECRET: clave_distinta_para_refresh
      GOOGLE_CLIENT_ID: 287573324529-6dratpth8ik6jr9ppdpf2nv666e0mv9b.apps.googleusercontent.com
      NODE_ENV: production
      SQL_BENCHMARK: '1'
      SLOW_QUERY_MS: '200'
      SLOW_HTTP_MS: '300'
    networks:
      - gympoint-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  backend_canary:
    image: project-gympoint-backend:canary
    build: ../backend/node
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mitre280
      DB_NAME: gympoint
      DB_PORT: 3306
      PORT: 3000
      JWT_SECRET: clave_super_secreta_para_tokens
      JWT_REFRESH_SECRET: clave_distinta_para_refresh
      GOOGLE_CLIENT_ID: 287573324529-6dratpth8ik6jr9ppdpf2nv666e0mv9b.apps.googleusercontent.com
      NODE_ENV: production
      SQL_BENCHMARK: '1'
      SLOW_QUERY_MS: '200'
      SLOW_HTTP_MS: '300'
    networks:
      - gympoint-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    container_name: gympoint-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '3000:80'
    depends_on:
      - backend_stable
      - backend_canary
    networks:
      - gympoint-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  gympoint-network:
    driver: bridge

